version: '3.1'

services:
  app:
    build:
      context: .
    volumes:
      - .:/opt/webapp
    ports:
      - 3000:3000
      - 3035:3035
    command: bash -c "foreman start -f Procfile.dev-server"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=topcbl
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=top_home_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.9-alpine

  mail:
    image: schickling/mailcatcher
    ports:
      - "41080:1080"
      - "41025:1025"

volumes:
  db-data:
